In [28]:
import numpy 

ar_from_shape = numpy.ndarray((2,3)) #crea un array 2x3 con valori float casuali
print(ar_from_shape)

[[3.38706704e-319 0.00000000e+000 1.39776128e-315]
 [2.65437718e+232 6.32539335e-310 6.32539333e-310]]


In [30]:


ar = numpy.array([1, 'hello', True])


ar.dtype, ar




(dtype('<U21'), array(['1', 'hello', 'True'], dtype='<U21'))

In [34]:
#creo una matrice 
diag1 = numpy.array( 
    [[1, 0],
     [0, 1]]
)
print("La taglia della matrice è: ", diag1.shape) 
print("Il numero di elementi della matrice è:", diag1.size)

La taglia della matrice è:  (2, 2)
Il numero di elementi della matrice è: 4


In [46]:
#creo una matrice diagonale e alla funzione "diag()" passo i valori che
# voglio dare agli elementi nella diagonale principale. Il numero di valori che metto
# sarà la taglia della matrice

matrice_1 = numpy.diag((1,1,1))
print ("La matrice ha dimensione: ", matrice_1.shape)
print (matrice_1)

#creo una  matrice identità. Alla funione identity() passo la taglia della matrice
identita_1 = numpy.identity(4)
print ("La matrice identità creata, ha dimensione: ", identita_1.shape)
print(identita_1)

La matrice ha dimensione:  (3, 3)
[[1 0 0]
 [0 1 0]
 [0 0 1]]
La matrice identità creata, ha dimensione:  (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [54]:
#creo un array di interi (valore di partenza, valore finale
X = numpy.linspace(1,int(1e+3),int(1e+3))
print(X)

[   1.    2.    3.    4.    5.    6.    7.    8.    9.   10.   11.   12.
   13.   14.   15.   16.   17.   18.   19.   20.   21.   22.   23.   24.
   25.   26.   27.   28.   29.   30.   31.   32.   33.   34.   35.   36.
   37.   38.   39.   40.   41.   42.   43.   44.   45.   46.   47.   48.
   49.   50.   51.   52.   53.   54.   55.   56.   57.   58.   59.   60.
   61.   62.   63.   64.   65.   66.   67.   68.   69.   70.   71.   72.
   73.   74.   75.   76.   77.   78.   79.   80.   81.   82.   83.   84.
   85.   86.   87.   88.   89.   90.   91.   92.   93.   94.   95.   96.
   97.   98.   99.  100.  101.  102.  103.  104.  105.  106.  107.  108.
  109.  110.  111.  112.  113.  114.  115.  116.  117.  118.  119.  120.
  121.  122.  123.  124.  125.  126.  127.  128.  129.  130.  131.  132.
  133.  134.  135.  136.  137.  138.  139.  140.  141.  142.  143.  144.
  145.  146.  147.  148.  149.  150.  151.  152.  153.  154.  155.  156.
  157.  158.  159.  160.  161.  162.  163.  164.  1

In [69]:
def func_naive (x, y=10) :
    from math import exp
    return exp(x)/y

X = numpy.linspace(0.0,1.0,100)
print (X)
func_naive(X)

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

TypeError: only length-1 arrays can be converted to Python scalars

In [71]:
ar = numpy.arange(0, 100, 11)
print(ar)

[ 0 11 22 33 44 55 66 77 88 99]


In [79]:
# a[start:stop:step]
print ( ar[0:100:3]) #elemento 3,6,9

[ 0 33 66 99]
